# Exported from Render on 2024-04-22T08:55:48Z
services:
- type: web
  name: newspaper
  runtime: python
  repo: https://github.com/somchit-khanthavong/newspaper_django_test
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./build.sh
  startCommand: python -m gunicorn newspaper.asgi:application -k uvicorn.workers.UvicornWorker
version: "1"
